### ISSUE TITLE
[BUG] build.sh script fails

### ISSUE THREAD

**Issue by pavll** [zekroTJA/shinpuru#108]
## Type of Bug

- [ ] Spelling
- [ ] Minor
- [ ] Major
- [ ] Crash

# Type of Host

- [ ] Public Canary
- [ ] Public Stable
- [x] Self Hosted

## Description

The getSqlSheme.bash does not exists in scripts folder.

## Steps to Reproduce

Run build.sh.

**Comment by zekroTJA** [comment]
The `build.sh` is outdated. I will remove this script later to avoid further confusion.

Also I noticed that the self-compiling guide in the wiki is outdated, so I've updated it.

Pelase consider using the Makefile to build shinpuru or go through the step-by-step guide.
https://github.com/zekroTJA/shinpuru/wiki/Self-Compiling
