### ISSUE TITLE
[FEATURE]  Add Option to disable Vote Result Image

### ISSUE THREAD

**Issue by zori4004** [zekroTJA/shinpuru#128]
## Type of Feature Request

- [ ] New feature
- [x] Enhancement

## Description
Adding a Way that the Result Image is not send for Votes/Polls.
Can be in Command e.g. sp!vote Frage? | 1 | 2 | false  => the false stands that the image doesnt send at the end.

## Images and Sketches
![vote_chart_735151505694261390](https://user-images.githubusercontent.com/59896907/88072478-5bcd1300-cb75-11ea-8ff0-ccc7fe540d22.png)

**Comment by zekroTJA** [comment]
First of all, than you verry much for the suggestion!

> Can be in Command e.g. sp!vote Frage? | 1 | 2 | false => the false stands that the image doesnt send at the end.
Nice idea, but I would rather suggest to put this in the close sub-command.
```
sp!vote close <voteID> (nochart|skipchart|nc|sc)
```
Example:
```
sp!vote close 681886690436317244 nc
```

**Comment by zori4004** [comment]
Jea thats true, perfekt! 😉👍
