### ISSUE TITLE
[FEATURE] Twitch Notification Image caching bypass

### ISSUE THREAD

**Issue by SnowLeoo** [zekroTJA/shinpuru#129]
## Type of Feature Request

- [ ] New feature
- [x] Enhancement

## Description

For the Twitch Notification there will only be shown the last cached Image because of Discords Caching.
You could bypass this Caching by giving the Stream Image always a new Name.

**Comment by zekroTJA** [comment]
Yeah, I've also discovered this issue some time ago. Giving random names would be a nice and easy solution. Thank you. ^^
