### ISSUE TITLE
[FEATURE] Karma system suggestions

### ISSUE THREAD

**Issue by SnowLeoo** [zekroTJA/shinpuru#145]
## Type of Feature Request

- [ ] New feature
- [x] Enhancement

## Description
> Please describe your feature request as clear and concise as possible.
### Some suggestions for the new Karma system
- Add Settings for Admins and Guild Owners
  - Enable/Disable Emojis, Limit of Karma etc.
- Make the Scoreboard more accessable 
  - e.g. You could provide it on the right side of the Web Interface
![XMheGxNjUH](https://user-images.githubusercontent.com/49914615/89287369-24219900-d654-11ea-8abb-2356af21b75f.png)

## Images and Sketches
> If you want to attach images or sketches, feel free to do it here.
/

**Comment by zekroTJA** [comment]
I split this issue in two for better overview. So, this issue holds dthe front end design change of the karma scoreboard.

The admin control of the karma system is now located in the issue #146.
