### ISSUE TITLE
[ENHANCEMENT] Permission settings in web interface should be a bit more "fuzzy"

### ISSUE THREAD

**Issue by rmcproductions** [zekroTJA/shinpuru#148]
## Type of Bug

- [ ] Typo
- [x] Minor
- [ ] Major
- [ ] Crash

## Description
> When I tried to add permissions for my guild (435444862972592129) from the webinterface, it didn't apply the permissions or update anything. Using the `sp!perms` command in chat showed the same result.
There are no errors in the DevTools console.
Adding the permissions via the chat command (`sp!perms +sp.guild.mod.mute Moderator`) worked perfectly and was displayed correctly both in the `sp!perms` overview and in the webinterface.

I can imagine that it has to do with how you select the role that you want to assign the permissions to. I tried both entering the name and the ID, both resulting in the same error. Maybe it'd be a good idea to make it a dropdown there aswell, like for the autorole settings?

## Steps to Reproduce
> Described above

## Images and Logs
> 
![image](https://user-images.githubusercontent.com/40141421/89533503-cf1c8900-d7f3-11ea-99df-25bd9d4eb061.png)

---

EDIT:

This issue is transformed to enhance the permission setting input which should be more "fuzzy", so it is case insensitive and also accepts pure role IDs.

**Comment by zekroTJA** [comment]
As I assume from the screenshot, you used the ID of the role, right? 

Actually, the field is ment to be used with role names and also has an "autocomplete" function to pick roles.
![kJxPuVRXwI](https://user-images.githubusercontent.com/16734205/89534298-fd4e9880-d7f4-11ea-93b0-0e7197e4d3c8.gif)

But yeah, actually, it should be possible to also use the role IDs. ^^

**Comment by rmcproductions** [comment]
I have tried using both the Name and ID. However, the autocomplete function doesn't work for me (see screenshot)

I'm on Opera 71 with the following UA: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.26 Safari/537.36 OPR/71.0.3770.0 (Edition developer)`

![image](https://rickast.li/gOXU9/wOcUkUJE61.gif/raw)

**Comment by zekroTJA** [comment]
Try to use lowercase letters, for some reason I#ve missed the lowercasing for that. This is actually an issue I am aware of but was too lazy until now to fix this. :D

**Comment by rmcproductions** [comment]
Ohhh I see! I didn't think about that honestly. Well that's good to know then, it works for me now :)

**Comment by zekroTJA** [comment]
I've transformed the issue to an enhancement issue to improve the permission input in the web interface and added it to the release 1.2 raodmap.

Thanks for the issue anyway. :)
