### ISSUE TITLE
[FEATURE] Increase thumbnail sizes for the guild overview

### ISSUE THREAD

**Issue by rmcproductions** [zekroTJA/shinpuru#163]
## Type of Feature Request

- [ ] New feature
- [x] Enhancement

## Description
The images for the user list are displayed quite small, so discord's default resolution for the images is sufficient. But the guild images are displayed much bigger, which makes them look blurry because they are being upscaled.

You can prevent this by appending `?size=2048` to the query string for the image (e.g. `https://cdn.discordapp.com/icons/307084334198816769/ce26a92d8c4f4ccd021c1f6fa28c27f1.png?size=2048`). This will always load the highest possible resolution - which is of course adjustable to 1024, 512, 256, etc. if you already know how big the image is gonna be displayed. 
I've done this manually for 3 guilds as you can see in the attached screenshots. It's quite a small change but it improves the visual quality by a lot if you ask me.

## Images and Sketches
[BEFORE]
![image](https://user-images.githubusercontent.com/40141421/92369542-6fb6df00-f0f9-11ea-9eb6-0787acdf2b22.png)

[AFTER]
![image](https://user-images.githubusercontent.com/40141421/92369859-d5a36680-f0f9-11ea-9196-0202327d6bfd.png)

**Comment by zekroTJA** [comment]
Well, did not know that you can specify a resolution for guild avis. Thats great, thank you!
Should be really easy to implement I guess. ^^

**Comment by rmcproductions** [comment]
Not just guild avis, also profile pictures and basically any image that's not an attachment :)
