### ISSUE TITLE
[FEATURE] Channel Locking

### ISSUE THREAD

**Issue by voxain** [zekroTJA/shinpuru#165]
## Type of Feature Request

- [x] New feature
- [ ] Enhancement

## Description
A command which locks the channel for chatting, which is done by removing the write permissions for every role in the channel the command was used in (except the highest role of the executor and the roles above, so the executor isn't locked out of the channel). If the command is used again, it unlocks the channel.
The idea behind this is to quickly prevent single-channel spam or a channel-targeted raid. Optionally, an admin (or someone with the permissions could lock the entire server).

The bot would have to remember the channel permission overrides on locking and would have to restore them accordingly on unlock.

**Comment by zekroTJA** [comment]
Do you think a channel lock event should be printed in the mod log? 

In my opinion, it is not nessecary, but just wanna get another opinion. ^^

**Comment by voxain** [comment]
I'd also say no. If you can easily, I'd make it optional, but if it's too much work, just don't log it.

**Comment by zekroTJA** [comment]
I would prefer to modify the functionality of this command to the way the `mute` command works:

There is a `lock init` command which either creates a `shinpuru-lock` role on the guild or uses a passed role to be used for this. This role can then be placed by the admins at a desired role level. The role will then be added to a locked channel with write permissions denied.
