### ISSUE TITLE
[BUG] Channel Lock doesn't work

### ISSUE THREAD

**Issue by SnowLeoo** [zekroTJA/shinpuru#169]
## Type of Bug

- [ ] Typo
- [ ] Minor
- [x] Major
- [ ] Crash

## Description
> Describe the bug as clear and concise as possible.
If you try to lock a channel, shinpuru first says that you don't have permissions to lock the channel but right after that it locks the channel. I think the perms aren't set right.

## Steps to Reproduce
> Enter stepwise how to reproduce the bug.
Just enter sp!lock or spc!lock as a normal User

## Images and Logs
> Here you can embed images or crash logs or command lines.
> Please use embeded markdown images and code blocks for that.
https://media.discordapp.net/attachments/509116688529227778/766640089668517908/image0.jpg?width=558&height=702

**Comment by zekroTJA** [comment]
Well, this was a way more serious bug which basically allowed every user with no permission to execut every command. Tahnks for the issue, it should be fixed now. ^^
