### ISSUE TITLE
[BUG] Error in the numbering.

### ISSUE THREAD

**Issue by ShowMeYourSkil** [zekroTJA/shinpuru#171]
## Type of Bug

- [ ] Typo
- [x] Minor
- [ ] Major
- [ ] Crash

## Description
> Describe the bug as clear and concise as possible.

  The table of sp!karma is wrong. 
- It is difficult to explain. Have a look at the screenshots below and you will understand what I mean

## Steps to Reproduce
> Enter stepwise how to reproduce the bug.
1. sp!karma
2. See table of Shinpuru and Shinpuru Canary

## Images and Logs
> Here you can embed images or crash logs or command lines.
> Please use embeded markdown images and code blocks for that.

 `Shinpuru Canary`

![image](https://user-images.githubusercontent.com/39274150/96457892-99971180-1220-11eb-9940-00765f995e9a.png)

`Shinpuru`

![image](https://user-images.githubusercontent.com/39274150/96458074-cd723700-1220-11eb-8b55-2affef375e02.png)

**Comment by zekroTJA** [comment]
Well, found the problem:
https://github.com/zekroTJA/shinpuru/blob/22e0b13cba4fd75cee5f770530583b3879facf11/internal/commands/cmdkarma.go#L74-L78

When a karma record in the database is linked to a user which is not a member of the guild anymore, the loop will continue and the position counter increases even if no new output entry was added eventually.
