### ISSUE TITLE
[FEATURE] Allow to report and ban members which are not on the guild

### ISSUE THREAD

**Issue by zekroTJA** [zekroTJA/shinpuru#189]
## Type of Feature Request

- [ ] New feature
- [x] Enhancement

## Description

Make it able to kick and ban members, by ID, which are not or no more on the given guild.

**Comment by KokosnussDEV** [comment]
This reminds me of "factions" where when you ban a member on one server who is then not able to join any server with your bot if the guild is in the "faction" the user is banned in

**Comment by zekroTJA** [comment]
Well, thats also a very inetersting idea, tho, it would be a whole new feature issue.

**Comment by KokosnussDEV** [comment]
I can open one to discuss it if you like to?

**Comment by zekroTJA** [comment]
> I can open one to discuss it if you like to?

Sure. ^^

**Comment by zekroTJA** [comment]
fixed with #193
