### ISSUE TITLE
[FEATURE] Blacklist people from code execution and color reactions

### ISSUE THREAD

**Issue by Ron31** [zekroTJA/shinpuru#197]
## Type of Feature Request

- [ ] New feature
- [x] Enhancement

## Description
Some persons often use the code execution or color buttons.
Implement a blacklist in the adminpanel where you can exclude users from this.

**Comment by zekroTJA** [comment]
In the both commits ae39dba and c2aa57f, I've added permission rules to execute code snippets in chat (`sp.chat.exec.exec`) and (`sp.chat.colorreactions`). These can now be disallowed *(or explicitely allowed)* a role base. It's not exactly a blacklist, but maybe this solves the issue too and also re-uses existing features and workflows. ^^
