### ISSUE TITLE
[FEATURE] Karma Mute

### ISSUE THREAD

**Issue by Kaktushose** [zekroTJA/shinpuru#201]
## Type of Feature Request

- [ ] New feature
- [x] Enhancement

## Description
> While a healthy amount of memes is good, some users tend to abuse the karma system. Therefore it would be nice to have a feature where you can mute users so their karma votes no longer count

**Comment by zekroTJA** [comment]
![meme](https://user-images.githubusercontent.com/16734205/106500747-79831980-64c2-11eb-992f-011c5631d501.png)
