### ISSUE TITLE
[FEATURE] Webinterface Autocompletition for permissions

### ISSUE THREAD

**Issue by voxain** [zekroTJA/shinpuru#203]
## Type of Feature Request

- [ ] New feature
- [x] Enhancement

## Description
Title says it. I want this.

![perm1](https://user-images.githubusercontent.com/40141421/108698643-aa280300-7504-11eb-853c-91639f5cfcb9.png)
![perm2](https://user-images.githubusercontent.com/40141421/108698651-abf1c680-7504-11eb-8891-db291bdeb55f.png)

**Comment by zekroTJA** [comment]
Oh yeah, that would be a really great idea. Should even be relatively easy to implement, because the API supplies all registered permissions available.

**Comment by zekroTJA** [comment]
![HV5qi2D9Ca](https://user-images.githubusercontent.com/16734205/109003709-13944700-76a8-11eb-92db-1eff56d1b520.gif)

**Comment by voxain** [comment]
That made me hornier than it should have
