### ISSUE TITLE
[FEATURE] Add link to unban requests to ban messages

### ISSUE THREAD

**Issue by zekroTJA** [zekroTJA/shinpuru#204]
In attachment to #196, the `host.tld/unbanme` URL should be mentioned in the ban message so that banned people are able to send unban requests.

**Comment by voxain** [comment]
I suggest adding a checkbox in the webinterface which decides if the banned user will also receive a message with the unban link, so one doesn't always have to manually append it. When banning from chat, the confirmation embed should have that enabled by default, but with a third emoji reaction to circumvent that from happening.

**Comment by zekroTJA** [comment]
Yeah, I actually ment that the URL is directly embeded in the ban notification message without the need of mentioning it in the actual ban reason message.

And yeah, an option whether to embed the unban link would also be nice, but therefore I would need to change some structural stuff. First of all, I think its important to inform people that they can send unban requests instead of annoying guild admins to unban them. ^^
