### ISSUE TITLE
[FEATURE] Starboard

### ISSUE THREAD

**Issue by zekroTJA** [zekroTJA/shinpuru#212]
⭐🛹

- [x] command to set starboard setting
      - channel
      - threshold 
      - emoji
- [x] listener + database bindings
- [x] web scoreboard with most stared messages / most recent stared messages on the guild
- [x] karma system implementation

**Comment by Kaktushose** [comment]
RIP https://github.com/dev-schueppchen/RonBoard
2021 - 2021

**Comment by zekroTJA** [comment]
> RIP https://github.com/dev-schueppchen/RonBoard
> 2021 - 2021

its actually just a skid :hAA:

**Comment by Kaktushose** [comment]
This is the *communism* way

**Comment by zekroTJA** [comment]
Fixed with #214.
