### ISSUE TITLE
[FEATURE] Add special Roles for Users with a specific amount of Karma

### ISSUE THREAD

**Issue by SnowLeoo** [zekroTJA/shinpuru#231]
## Type of Feature Request

- [x] New feature
- [ ] Enhancement

## Description
Give users who are active in a server some privileges to a Role which gives them access to a channel or something like it.

Example:
You could add it to the Karma Webboard and define a Role and a Karma amount what you need to get this Role

-->No sketch

**Comment by Ron31** [comment]
Maybe also something like:
if you are under this karma amount (as example below -10 Karma) you can also get another role

**Comment by zekroTJA** [comment]
> Maybe also something like:
> if you are under this karma amount (as example below -10 Karma) you can also get another role

Auto ban when under a certain karma threshold kekw

**Comment by MathisBurger** [comment]
Autobanning user sounds like an good idea.
But the karma limit should be very low to prevent troll bans.
