### ISSUE TITLE
Anonymous report not anonymous

### ISSUE THREAD

**Issue by Skillkiller** [zekroTJA/shinpuru#270]
## Description

Anonymous reports are not anonymized. If you create an anonymous report using the web interface, the executor will still be listed in the report. Both in the web interface and in the modlog channel.
Because the executor is also displayed in the modlog channel, it is also impossible that it is only displayed because of increased rights.

## Steps to Reproduce

1. Open Webinterface and choose a guild
2. Open Modlog
3. Click "Create Anonymous Report"
4. Fill the form
5. Click "EXECUTE"
6. Look in Modlog or Modlog Channel

## Images and Logs

https://user-images.githubusercontent.com/18444809/128711844-a60743ea-4986-4851-b6f7-acc1c842d090.mp4

**Comment by zekroTJA** [comment]
Well, okay, I really need to change the wording for this feature. 

Anonymous reports do not anonymize the report executor. They allow to report someone by user ID without that the user is a member of the guild where the report is created for. So you can ban or report someone after the person quit the guild, for example.

**Comment by Skillkiller** [comment]
This was also explained to me today on the server:
![image](https://user-images.githubusercontent.com/18444809/128724244-bd55190b-1883-4c94-9561-2acd9a1827a8.png)
