### ISSUE TITLE
Antiraid Joinlog should contain more detailed information

### ISSUE THREAD

**Issue by zekroTJA** [zekroTJA/shinpuru#283]
### Type

Enhancement of an existing feature

### Description

The current Antiraid Joinlog only logs the timestamp, user ID and user tag. Also, following information should be directly included into the join log to better evaluate the legitimacy of a user.

- The creation date of the account (can be derived from the user ID snowflake) as well as the Age (only in the web interface)

**Comment by SnowJuli** [comment]
Would like to look into it. The joinlog is in the listeners directory, right?

**Comment by zekroTJA** [comment]
Yep, its this to be concise. ^^

https://github.com/zekroTJA/shinpuru/blob/master/internal/listeners/antiraid.go
