### ISSUE TITLE
`/mute toggle` slash command does not work

### ISSUE THREAD

**Issue by zekroTJA** [zekroTJA/shinpuru#312]
### Type

Functional Issue

### Instances

- [X] Canary
- [X] Stable
- [X] Self-Hosted

### Description

The `/mute toggle` slash command fails to apply the set mute role.

### Steps to reproduce

1. Use `/mute setup` to set up a mute role.
2. Mute a member with `/mute toggle <user>`.

### Attachments

![image](https://user-images.githubusercontent.com/16734205/144055894-cb3f0b09-3787-481f-8217-f09e1d45f53e.png)

## Workaround

The `sp!mute` command is still available and works properly to mute toggle members.

**Comment by voxain** [comment]
While youre at it, what do you think about making the mute role configurable? Lets say you already have a mute role set up, either by another bot or by yourself, because the mute role still needs specific permissions - you think there would be a way to make it choosable?
