### ISSUE TITLE
Join rule accept

### ISSUE THREAD

**Issue by zekroTJA** [zekroTJA/shinpuru#364]
### Type

Enhancement of an existing feature

### Description

A feature where users need to accept the guild rules, for example, via a reactions - or better via a component button - in a channel. After that, they will get assigned a role which allows read-write access to all other channels.

**Comment by zordem** [comment]
(or via modals) ((would be dope uwu))

**Comment by zordem** [comment]
If you use a component button you can reply the user with a modal. Discord uses "modals" too for accepting rules.

**Comment by zordem** [comment]
My reasoning behind that is the following: People to accept something on a modal is more engaging then just a button. ANd more engagion for rules is better in my opinion.

**Comment by TomRomeo** [comment]
Modals don't have any type of buttons though, right?

What would users be expected to write into the textinput inside of that modal?

**Comment by zordem** [comment]
Yes you are right, i wasn't aware of that. Forgot my comment. Having a text field where users type "I accept" or something is not a good solution.

**Comment by zekroTJA** [comment]
I think this feature is obsolete by now because Discord has a native feature now which actually does this in a similar way.
