### ISSUE TITLE
Improve Duration decoding

### ISSUE THREAD

**Issue by zekroTJA** [zekroTJA/shinpuru#372]
### Type

UI/UX Enhancement

### Description

Currently, commands which take time spans as parameter should also be able to handle time formats like days `d` or weeks `w` and should generally be less strictive as the default Go implementation.

#### Idea

This could be easily achieved using the following regex.
```regex
(?Uis)(?:(?<w>\d+)w)?(?:(?<d>\d+)d)?(?:(?<h>\d+)h)?(?:(?<m>\d+)m)?(?:(?<s>\d+)s)?
```

**Comment by lus** [comment]
You could also use `github.com/karrick/tparse` like I did in one of my projects:
https://github.com/lus/jacques/blob/main/internal/discord/reminder.go#L107

This package implements more advanced duration notations (you could actually provide `1d-1h` and would end up with a duration of 23 hours).

**Comment by zekroTJA** [comment]
Yeah, thank you for the recommendation, but I already implemented something to handle it. ^^
