### ISSUE TITLE
Banning Member that is no longer on the Guild results in Exception

### ISSUE THREAD

**Issue by Kaktushose** [zekroTJA/shinpuru#378]
### Type

Breaking Issue

### Instance

Main Stable (shinpuru#4878 / shnp.de)

### Description

When banning a member that is no longer on the Guild, e.g. he left, the ban command fails and throws an exception. 

![image](https://user-images.githubusercontent.com/42280757/179018265-18763bc2-7cbe-4c87-ad66-f4b5f7538c42.png)

Expected behavior would be that the member gets banned nonetheless, using the user object

### Steps to reproduce

1. type ban command for member
2. member leaves
3. execute command

**Comment by zekroTJA** [comment]
That's a really interesting use case actually. Anonymous reports are possible at the moment only via the web interface, but actually, it would also be nice to make it possible via the slash command interface. 🤔

**Comment by Kaktushose** [comment]
I mean just ban the User instead of the Member and this edge case is covered

**Comment by zekroTJA** [comment]
> I mean just ban the User instead of the Member and this edge case is covered

I know what you mean and yes, thats the fix I've implemented for now. But also it would be nice if you could do anonymous bans using slash commands instead of being able to do it only in the web interface.
