### ISSUE TITLE
WebInterface Rework/Beta: Login via Code not working

### ISSUE THREAD

**Issue by LiebesWavezLP** [zekroTJA/shinpuru#388]
### Type

Functional Issue

### Instance

Main Canary (shinpuru Canary#3479 / c.shnp.de)

### Description

(This issue is only working only with no already existing Cookies or if u have never login into the webinterface in canary-beta before(First Login)) Login into the Beta-Interface in Shinpu Canary via Code-Login not working. (https://c.shnp.de/beta/login)

There are 2 Scenarios
I try to write the Canary Bot the Token, if i had do that i got redirected to [..]
1. to the Login interface without a successfull login and i need login again
2. To the Mainpage without login successfully.
3. https://c.shnp.de/beta/db but without any informations (see Screenshot)

This Login Method is working on the normal Shinpu Beta WI-Login (https://shnp.de/beta/login) and its working on Canary-Beta if u was already logged in, at least 1 time (For me i had logged in with OAuth then and it worked after that).

### Steps to reproduce

!Important! Clear Cookies for the site https://c.shnp.de/
1. Go to https://c.shnp.de/beta/
2. Accept the Beta Warning
3. Press on "Go to Login"
4. Copy the Login Code from the Bot and send it to shinpuru Canary

### Attachments

![image](https://user-images.githubusercontent.com/33105443/189311462-896b63b6-d260-43e5-ada9-5360b7c2a1cc.png)

**Comment by zekroTJA** [comment]
Thank you for the issue. Well, that is actually sort of a known issue. But I am actually putting this off for a while now because I was not able to find the reason yet. I'll look into it again when I find the time to do so.
