### ISSUE TITLE
Free Karma at Birthdays

### ISSUE THREAD

**Issue by boloped** [zekroTJA/shinpuru#399]
### Type

Enhancement of an existing feature

### Description

It would be cool to link the birthday notifitcation feature with the karma system. People should get a small amount of Karma (e.g. 10) at their birthdays.

**Comment by boloped** [comment]
(please add this as a birthday gift lmao)

**Comment by voxain** [comment]
Karma is supposed to be rewarding for making helpful comments or saying something based. Giving it out for free just for existing kinda doesn't fit the purpose. Hör auf zu geiern aus den -100 kommst du eh nicht mehr raus

**Comment by boloped** [comment]
kekw

**Comment by zekroTJA** [comment]
Honestly, I am with @voxain here. It would be sort of pointless in respect of the purpose of the karma system to gift karma on birthdays. Also, it would be unfair for people who simply don't want their birthdays to be public. This could also invite to simply register wrong birthday dates to get the free karma. Also, people could change their birthday date every day and get free karma every day that way and I really don't want to build in prohibitions to circumvent this.

**Comment by boloped** [comment]
ok sorry I was extremly stupid. I agree with both of you now. Have a great day guys!
