### ISSUE TITLE
Invisible text for landing page

### ISSUE THREAD

**Issue by DustinDEV2more** [zekroTJA/shinpuru#421]
### Type

Visual Issue

### Instance

Main Stable (shinpuru#4878 / shnp.de)

### Description

The scrolling Text under "And much more to be discovered ..." is invisible. 

### Steps to reproduce

1. Open any browser at https://shnp.de/start
2. Scroll to the bottom of the page

### Attachments

![image](https://user-images.githubusercontent.com/45263590/229875372-2095b1ba-5f42-4ac8-bf8a-d9936d9c7c06.png)
![image](https://user-images.githubusercontent.com/45263590/229875494-d5fd0141-6b1a-47fa-81b4-29068de14799.png)

**Comment by zekroTJA** [comment]
Yeah, seems like there is an issue with the `background-clip: text` support on chromium based browsers. According to [Can I Use](https://caniuse.com/background-clip-text) and [this article](https://mgearon.com/css/css-background-clip-text), it should work when using the `-webkit-` prefix. I'll try it out and put "testing everything frontend related also with chrome" to my checklist.

Tank you very much for the report. <3

**Comment by voxain** [comment]
@zekroTJA For this purpose, I don't know if you're using it yet, consider looking into autoprefixer or SASS with a compiler that does stuff like this for you automatically. It's the same plain CSS but you don't have to type the same thing for three browsers everytime.

**Comment by zekroTJA** [comment]
> @zekroTJA For this purpose, I don't know if you're using it yet, consider looking into autoprefixer or SASS with a compiler that does stuff like this for you automatically. It's the same plain CSS but you don't have to type the same thing for three browsers everytime.

@voxain As far as described in the docs, styled-components should do that automatically. But why ever not not in this case, I don't know.
![image](https://user-images.githubusercontent.com/16734205/229911648-8b37b343-2c9e-4ac6-8b5f-d925117be9f6.png)

**Comment by voxain** [comment]
Weird. Welcome to the world of web development i guess..
