### ISSUE TITLE
Notification for unban requests

### ISSUE THREAD

**Issue by voxain** [zekroTJA/shinpuru#423]
### Type

A new feature

### Description

Correct me if I'm overseeing something, but Im currently looking for a way to get notified for new unban requests, since thats a quite essential feature that youd need to be informed about without always checking the webinterface which i dont think should be necessary.

So I think itd make sense to notify admins of new unban requests, either on a per user basis by DMing said admins or setting a general broadcast channel in discord for these kind of actions.

**Comment by itsDkiller** [comment]
I'd use a broadcast channel for this. A guild admin should be able to configure which one of the guild channels is going to be used for this feature.

**Comment by itsDkiller** [comment]
The downside of notifying per direct message is that a guild admin could've DM's configured to be disabled.

**Comment by voxain** [comment]
> The downside of notifying per direct message is that a guild admin could've DM's configured to be disabled.

Very true. Though I'm always a fan of "Better haben than brauchen"
