### ISSUE TITLE
Optimize tag command

### ISSUE THREAD

**Issue by Kaktushose** [zekroTJA/shinpuru#439]
### Type

Enhancement of an existing feature

### Description

# Problem
All `/tag` commands (except for `/tag list`) require the tag name as an option. But remembering all tag names is very hard. This results in:
- invalid command executions
- excessive use of `/tag list`
- and ultimately avoidance of using tags at all

# Solutions
This issue could be resolved in three different ways

## a) using choices
The name option could use [choices](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-choice-structure) instead.

**Pros**:
- the user can directly see all the tags that are available

**Cons**:
- you can only add up to 25 choices
- all tag commands need to be updated everytime a tag gets added/deleted/modified

## b) using autocomplete
[autocomplete](https://discord.com/developers/docs/interactions/application-commands#autocomplete) allows the bot "[...] to dynamically return option suggestions to a user as they type".

**Pros**:
- easy to implement
- allows unlimited amount of choices

**Cons**:
- user still has to remember the tags to a certain extend 

## c) using both choices and autocomplete
This approach combines the both solutions discussed prior. The bot would use choices for up to 25 tags. After that, autocomplete would be used instead. This is by far the most complex solution, but it would also provide the best user experience. 

# Conclusion
From my perspective both as a user and a developer I'd prefer solution b) since tags are more of a niche feature and the cost-benefit factor does not pay off with the other solutions

**Comment by zekroTJA** [comment]
Requires zekrotja/ken#18.

**Comment by zekroTJA** [comment]
I've decided on your option B). Command auto completion has now been implemented in Ken and also beein implemented for the tag command. Because, when no input is presented, the full list of tags (capped to 30 at max) is shown to the user, so they don't even need to remember most of the tags at all.

Thank you very much for your feedback! :)
