### ISSUE TITLE
[BUG] Anyone can ping everyone or here using the ghost ping feature.

### ISSUE THREAD

**Issue by Eli-dev** [zekroTJA/shinpuru#45]
## Type of Bug

- [ ] Spelling
- [ ] Minor
- [x] Major
- [ ] Crash

## Description
> Anyone can ping @everyone or @here using the ghost-ping feature. A easy solution is to use embeds.

## Steps to Reproduce
> @mention someone and put \\\@everyone or \\\@here in the same message. Then delete the message.

**Comment by zekroTJA** [comment]
I've changed the status of the issue to `Major`/`Critical` because members with roles having no permission to mention @ everyone could abuse this when the bot has the permission to mention everyone set.
