### ISSUE TITLE
[BUG] ghost ping mention when bot deletes mentioned commands

### ISSUE THREAD

**Issue by Eli-dev** [zekroTJA/shinpuru#47]
## Type of Bug

- [ ] Spelling
- [x] Minor
- [ ] Major
- [ ] Crash

## Description
> Bot sends ghost ping warning if someone executes the user command with a @mention.

## Steps to Reproduce
> Type !(or the local prefix if set)user @user

**Comment by Eli-dev** [comment]
Oh btw. probably also with other commands possible.

**Comment by Eli-dev** [comment]
OK. It's possible with every command where user messages are deleted.

**Comment by zekroTJA** [comment]
categorized as bug based on this vote:  
![](https://i.zekro.de/firefox_2019-02-20_16-42-03.png)
