### ISSUE TITLE
[BUG] Unable to set leave message channel

### ISSUE THREAD

**Issue by InterXellar** [zekroTJA/shinpuru#70]
## Type of Bug

- [ ] Spelling
- [ ] Minor
- [x] Major
- [ ] Crash

## Description
> It's not possible to set the leave message channel. (See picture below)

## Steps to Reproduce
> Try to set a leave message channel

## Images & Logs
> `[prefix]leavemsg channel #join-log`

![image](https://user-images.githubusercontent.com/25595421/63769381-f627c680-c8d2-11e9-9dc8-e2aa51eb2f2b.png)

**Comment by zekroTJA** [comment]
**Addition:**

Because of the shared functions this also refers to the `joinmsg channel` sub command.
