### ISSUE TITLE
[BUG] leavemsg is not being sent to the defined channel

### ISSUE THREAD

**Issue by InterXellar** [zekroTJA/shinpuru#73]
## Type of Bug

- [ ] Spelling
- [X] Minor
- [x] Major
- [ ] Crash

# Type of Host

- [ ] Public Canary
- [X] Public Stable
- [ ] Self Hosted

## Description
> The message set in the leavemsg command won't be sent to the defined channel

## Steps to Reproduce
1.  Set leavemsg channel `!leavemsg channel <channel>`
2.  Set leavemsg msg `!leavemsg msg <msg>`
3. Let another user leave, the leave message won't be sent

**Comment by zekroTJA** [comment]
Somehow I fixed this bug without mentioning the issue and now, I am too lazy to search for the commit where I have fixed it.
Now, it works and I think I can close this issue 😄
