### ISSUE TITLE
Potential Makefile typo?

### ISSUE THREAD

**Issue by anathemamask** [zekroTJA/shinpuru#85]
firing 'make' on current git clone (per the instructions for self hosting) returns 

'dep mod tidy
dep: mod: no such command
Dep is a tool for managing dependencies for Go projects

Usage: "dep [command]"
'

Should the line in the makefile calling '$DEP mod tidy' read '$GO mod tidy'?

cheers,

SM

**Comment by zekroTJA** [comment]
Oh yeah, of course, thank you verry much! :)
