### ISSUE TITLE
[BUG] Bots are allowed to execute commands

### ISSUE THREAD

**Issue by Lukaesebrot** [zekroTJA/shinpuru#90]
## Type of Bug

- [ ] Spelling
- [ ] Minor
- [x] Major
- [ ] Crash

# Type of Host

- [x] Public Canary
- [ ] Public Stable
- [ ] Self Hosted

## Description
> Other bots are able to execute commands

## Steps to Reproduce
> Use a bot to execute a command

## Images & Logs
https://rickast.li/HaXA9/japIvEcO20.png

**Comment by zekroTJA** [comment]
I really have no idea how I could have missed this. I've looked at this command handler and just realized I absolutely forgot about that. Thanks tho for the issue. ^^
